language: node_js
node_js:
- '5'
notifications:
  slack: garlictech:hWAwcbpZceCN9v67hEn1ynIR
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: contact@garlictech.com
  on:
    tags: true
    branch: master
  api_key:
    secure: b9SUmEp0V6M66bhSqaufZx30j5gvnx3LggUDiPW9BmLYa7Ov/oobm65+jyK+HtoGvru9Xsq75kfMbKBxnz85lmx1RVdn/ieKOQARlM2LqJSPeTUpZ2gK3HmIWg9eLZWXAZ3rVQLHbZX9qHF4N7jI4lTCTISkplNTOCgvZVbjBsPjAiehCZrowH51o1Njf2j445lEJy8mmxEdmCwk6bHi95b8XwMO6qmkSQ1opPsC8RzlOyyS/0zcxDGel7o2AXc+kRD3Ku0puyLbRDEjejTzDLDZeZFDCR4qS+kOhOiXupeQV9wGBc6m/NOb+MYSNkMTxJ9ss6pxncB5NY6Vd9yxQFVd3i2EqHNnVP5o8GtJkjhQc1CELhCRD/ZIn/UlJMjnrPL9SxUloN5IwtrQtHIEBjA60UNk9C8GNiqwTNN09NC2gq+q2DAx4VfrcbVqw453m9XhZ+25C8xisySP74wLyT92oUM3qRKwiH5lXmiukLe1yg5Q/pCw/xpAQvOvAhIK2pOEhqvQLgB0qBsyPUY+MMK7JNUmnl8JG4o1djnDAn9URaWYj/yCwo149JGvr4mMINxPwvCobfudS9TDnGeTB69HYHURgbU3d5V/IMhf5DWTeG+io+PA2trOxlspEVF0EHzvef70pJafbPa+gBiFgeUDDJsOqwTYysKOfBxgris=
